[workspace]

members = ["columnq", "columnq-cli", "roapi"]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = true
codegen-units = 1

[patch.crates-io]
convergence = { git = "https://github.com/returnString/convergence.git", rev = "2f95a74321e7ee4d59f3aea09788314a3eaf0eb9" }
convergence-arrow = { git = "https://github.com/returnString/convergence.git", rev = "2f95a74321e7ee4d59f3aea09788314a3eaf0eb9" }
