name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # NOTE: the version is also defined in roapi_http_release.yml, columnq_cli_release.yml and Dockerfile
  RUST_TC_NIGHTLY_VER: "2022-09-24"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-cpu=skylake"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          ${{ runner.os }}-cargo-
    - name: Install minimal stable with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true
    - name: Check
      run: cargo clippy
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Trim cache
      run: |
        which cargo-cache || cargo install cargo-cache
        cargo cache trim -l 1G

  simd_test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-cpu=skylake"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: simd-3-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
        restore-keys: |
          simd-3-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          simd-3-${{ runner.os }}-cargo-
    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        # toolchain: nightly
        toolchain: nightly-${{ env.RUST_TC_NIGHTLY_VER }}
        override: true
    - name: Run tests
      run: cargo test --features simd
    - name: Trim cache
      run: |
        which cargo-cache || cargo install cargo-cache
        cargo cache trim -l 1G

  database_test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-cpu=skylake"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: database-1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            database-1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
            database-1-${{ runner.os }}-cargo-
      - name: Install nightly rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly-${{ env.RUST_TC_NIGHTLY_VER }}
          override: true
      - name: Check
        run: cargo clippy --features database
      - name: Build
        run: cargo build --features database
      - name: Run tests
        run: cargo test --features database
      - name: Trim cache
        run: |
          which cargo-cache || cargo install cargo-cache
          cargo cache trim -l 1G

  s3_test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-cpu=skylake"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: s3-1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
        restore-keys: |
          s3-1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          s3-1-${{ runner.os }}-cargo-
    - name: Install nightly rust
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        # toolchain: nightly
        toolchain: nightly-${{ env.RUST_TC_NIGHTLY_VER }}
        override: true
    - name: Install minio server
      run: |
        docker run -d -p 9000:9000 quay.io/minio/minio server /data
    - name: Install minio client
      run: |
        curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc
        chmod +x $HOME/minio-binaries/mc
        export PATH=$PATH:$HOME/minio-binaries/
    - name: Setup buckets and test data
      run: |
        mc alias set local http://127.0.0.1:9000 minioadmin minioadmin
        mc mb local/test-data
        mc cp test_data/blogs.parquet local/test-data
    - name: Start roapi
      env:
        AWS_DEFAULT_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: minioadmin
        AWS_SECRET_ACCESS_KEY: minioadmin
        AWS_ENDPOINT_URL: http://127.0.0.1:9000
      run: cargo run --bin roapi -- -c test_s3.yml
    - name: Query roapi, Expect 200 response code
      run: if [ $(curl -o /dev/null -s -w "%{http_code}" -X POST -d 'SELECT count(1) from blogs' 127.0.0.1:8084/api/sql) != "200" ]; then exit 1; fi

  # make sure native-tls always builds
  openssl_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install minimal stable with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true
    - name: Check
      run: cargo clippy --no-default-features --features=native-tls
    - name: Trim cache
      run: |
        which cargo-cache || cargo install cargo-cache
        cargo cache trim -l 1G

  # cross compile from x86 mac to arm64, this is to make sure universal2
  # release will build without error
  mac_cross_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: mac-1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
        restore-keys: |
          mac-1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          mac-1-${{ runner.os }}-cargo-
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-${{ env.RUST_TC_NIGHTLY_VER }}
        target: aarch64-apple-darwin
        profile: minimal
        default: true
    - name: Build binary - universal2
      env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        MACOSX_DEPLOYMENT_TARGET: '10.9'
      run: |
        # set SDKROOT for C dependencies
        export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
        cd roapi && \
          cargo build --bin roapi --features database --target aarch64-apple-darwin
    - name: Trim cache
      run: |
        which cargo-cache || cargo install cargo-cache
        cargo cache trim -l 1G

  docker_build:
    name: Docker Image Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          load: true
          tags: roapi:latest
      - name: Test
        run: |
          docker run --rm roapi:latest --help
